"""
Velira GitHub PR Client
Creates auto-remediation PRs on the demo infrastructure repo
when critical GxP drift is detected.
Uses raw requests + GitHub REST API. Falls back to gh CLI if available.
"""

from __future__ import annotations

import base64
import json
import os
import shutil
import subprocess
import time
from datetime import datetime, timezone

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO_OWNER = os.environ.get("GITHUB_REPO_OWNER", "shreyanair612")
GITHUB_REPO_NAME = os.environ.get("GITHUB_REPO_NAME", "latch-demo-env")

TIER_EMOJI = {
    "critical": "\U0001f6a8",
    "suspicious": "\u26a0\ufe0f",
    "allowed": "\u2705",
}

TIER_BADGE = {
    "critical": "![CRITICAL](https://img.shields.io/badge/severity-CRITICAL-red)",
    "suspicious": "![SUSPICIOUS](https://img.shields.io/badge/severity-SUSPICIOUS-orange)",
    "allowed": "![ALLOWED](https://img.shields.io/badge/severity-ALLOWED-green)",
}

FILE_MAP = {
    "storage": "infrastructure/genomics-storage.tf",
    "nsg": "infrastructure/network-security.tf",
    "network": "infrastructure/network-security.tf",
    "iam": "infrastructure/iam-roles.tf",
    "role": "infrastructure/iam-roles.tf",
}


def _gh_env() -> dict:
    """Build a clean env for gh CLI calls, stripping GITHUB_TOKEN so gh uses its own auth."""
    env = os.environ.copy()
    env.pop("GITHUB_TOKEN", None)
    env.pop("GH_TOKEN", None)
    return env


def _gh_api(method: str, endpoint: str, data: dict | None = None) -> dict | None:
    """Call GitHub API via the gh CLI (used as fallback when PAT lacks write scope)."""
    cmd = ["gh", "api", "--method", method, endpoint]
    if data:
        for k, v in data.items():
            cmd += ["-f", f"{k}={v}"]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=_gh_env())
    if result.returncode != 0:
        print(f"[github_pr] gh api {method} {endpoint} failed: {result.stderr.strip()[:200]}")
        return None
    if not result.stdout.strip():
        return {}
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"raw": result.stdout.strip()}


def _gh_available() -> bool:
    if not shutil.which("gh"):
        return False
    try:
        r = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True, timeout=10, env=_gh_env())
        return r.returncode == 0
    except Exception:
        return False


def _resolve_filepath(resource_id: str) -> str:
    """Map resource_id to the appropriate Terraform file."""
    rid = resource_id.lower()
    for key, path in FILE_MAP.items():
        if key in rid:
            return path
    return "infrastructure/genomics-storage.tf"


def _build_pr_body(drift_event: dict, classification: dict, owner: str) -> str:
    tier = classification.get("tier", "critical")
    attribute = drift_event.get("attribute", "unknown")
    resource_id = drift_event.get("resource_id", "unknown")
    baseline_value = drift_event.get("baseline_value", "N/A")
    current_value = drift_event.get("current_value", "N/A")
    timestamp = drift_event.get("timestamp", datetime.now(timezone.utc).isoformat())
    regulation = classification.get("regulation_reference", "21 CFR Part 11.10(a)")
    reason = classification.get("reason", "No reason provided.")
    tier_badge = TIER_BADGE.get(tier, TIER_BADGE["critical"])

    return f"""\
## :microscope: GxP Compliance Drift — Auto-Remediation PR

**Generated by:** Velira Drift Detection System
**Severity:** {tier_badge}
**Detected:** {timestamp}
**Regulation:** {regulation}

---

### What Changed
| Field | Baseline (v3.2) | Current (Drifted) |
|-------|-----------------|-------------------|
| `{attribute}` | `{baseline_value}` | `{current_value}` |

### AI Compliance Assessment
{reason}

### Remediation
This PR restores `{resource_id}` to its FDA-validated baseline configuration (v3.2, validated 2025-01-15).

Apply and merge this PR to restore GxP compliance. All changes are logged in the Velira audit trail.

---
> :robot: Auto-generated by [Velira](https://github.com/{owner}/{repo}) | @qa-manager please review"""


def create_drift_pr(drift_event: dict, classification: dict) -> str | None:
    """
    Create a remediation PR on the demo infrastructure repo.

    Args:
        drift_event: Dict with resource_id, attribute, baseline_value, current_value, timestamp
        classification: Dict with tier, reason, regulation_reference, source

    Returns:
        The HTML URL of the created PR, or None on failure.
    """
    owner = GITHUB_REPO_OWNER
    repo = GITHUB_REPO_NAME
    full_repo = f"{owner}/{repo}"

    if not _gh_available():
        print("[github_pr] gh CLI not available — cannot create PR")
        return None

    tier = classification.get("tier", "critical")
    attribute = drift_event.get("attribute", "unknown")
    resource_id = drift_event.get("resource_id", "unknown")
    baseline_value = drift_event.get("baseline_value", "N/A")
    current_value = drift_event.get("current_value", "N/A")
    timestamp = drift_event.get("timestamp", datetime.now(timezone.utc).isoformat())
    regulation = classification.get("regulation_reference", "21 CFR Part 11.10(a)")
    reason = classification.get("reason", "")

    unix_ts = int(time.time())
    branch_name = f"velira/fix-{resource_id}-{unix_ts}"

    try:
        # Step 1: Get main branch SHA
        print(f"[github_pr] Step 1: Getting main branch SHA for {full_repo}")
        main_ref = _gh_api("GET", f"/repos/{full_repo}/git/ref/heads/main")
        if not main_ref or "object" not in main_ref:
            print("[github_pr] Failed to get main branch SHA")
            return None
        main_sha = main_ref["object"]["sha"]

        # Step 2: Create new branch
        print(f"[github_pr] Step 2: Creating branch {branch_name}")
        branch_result = _gh_api("POST", f"/repos/{full_repo}/git/refs", {
            "ref": f"refs/heads/{branch_name}",
            "sha": main_sha,
        })
        if branch_result is None:
            print("[github_pr] Failed to create branch")
            return None

        # Step 3: Determine file to update
        filepath = _resolve_filepath(resource_id)
        print(f"[github_pr] Step 3: Targeting file {filepath}")

        # Step 4: Get current file SHA
        print(f"[github_pr] Step 4: Getting file SHA for {filepath}")
        file_resp = _gh_api("GET", f"/repos/{full_repo}/contents/{filepath}")
        if not file_resp or "sha" not in file_resp:
            print(f"[github_pr] File {filepath} not found in repo")
            return None
        file_sha = file_resp["sha"]
        current_content = base64.b64decode(file_resp["content"]).decode()

        # Step 5: Generate remediation content
        remediation_block = f"""
# VELIRA AUTO-REMEDIATION — {timestamp}
# Drift detected: {attribute} changed from {baseline_value} to {current_value}
# Severity: {tier.upper()}
# Regulation: {regulation}
# Action: Restore to GxP validated baseline v3.2
# Justification: {reason[:200]}
"""
        updated_content = current_content + remediation_block

        # Step 6: Commit updated file to new branch
        print(f"[github_pr] Step 6: Committing remediation to branch {branch_name}")
        encoded_content = base64.b64encode(updated_content.encode()).decode()
        commit_result = _gh_api("PUT", f"/repos/{full_repo}/contents/{filepath}", {
            "message": f"velira: restore {attribute} on {resource_id} to GxP baseline",
            "content": encoded_content,
            "sha": file_sha,
            "branch": branch_name,
        })
        if commit_result is None:
            print("[github_pr] Failed to commit file")
            return None

        # Step 7: Open Pull Request
        tier_emoji = TIER_EMOJI.get(tier, TIER_EMOJI["critical"])
        pr_title = f"{tier_emoji} VELIRA: Restore {attribute} on {resource_id}"
        pr_body = _build_pr_body(drift_event, classification, owner)

        print(f"[github_pr] Step 7: Opening PR")
        # Use gh pr create for reliable PR creation
        pr_result = subprocess.run(
            ["gh", "pr", "create",
             "--repo", full_repo,
             "--base", "main",
             "--head", branch_name,
             "--title", pr_title,
             "--body", pr_body],
            capture_output=True, text=True, timeout=30, env=_gh_env(),
        )

        if pr_result.returncode != 0:
            print(f"[github_pr] PR creation failed: {pr_result.stderr.strip()[:200]}")
            return None

        pr_url = pr_result.stdout.strip()
        print(f"[github_pr] PR created: {pr_url}")
        return pr_url

    except Exception as e:
        print(f"[github_pr] Unexpected error: {e}")
        return None
